### ISSUE TITLE
Scrapped Mob Texture on the assets 

### ISSUE THREAD

**Issue by Mary5820** [HugoMage/Aquafina#4]
https://github.com/HugoMage/Aquafina/blob/main/main/resources/assets/aquafina/textures/entity/pygmy_right_whale.png

**Comment by Mary5820** [comment]
I think leaving the texture it would make people think it will be added, though devs have said that no whales

**Comment by HugoMage** [comment]
just because its on the github doesnt mean its gonna be added, the only good source of info is from the server that owns the mod, or by the owner himself
